services:
  matizev2:
    build: 
      dockerfile: Dockerfile
      context: ./
      target: development 
    restart: always
    container_name: matizeapi
    env_file:
      - .env
      - development.env
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
