services:
  matize-db:
    image: postgres
    container_name: matize-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=matize
      - POSTGRES_PASSWORD=845d47df5c3a993de0517f315ca8341a
      - POSTGRES_DB=matizedb
    expose:
      - '5432'
    ports:
      - 9000:5432
    volumes:
      - pgdata:/data/postgres
    command: -p 5432
  matizev2:
    build:
      dockerfile: Dockerfile
      context: ./
      target: development
    restart: always
    container_name: matizev2
    env_file:
      - .env
      - development.env
    ports:
      - 9012:80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
