services:
  matizeapi:
    build: ./
    restart: always
    container_name: matizeapi
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
